sudo: required
dist: trusty
services:
  - docker

language: go

go:
  - 1.13.7

os:
  - linux
  - osx

env:
  matrix:
    - TARGETS="check"
    - TARGETS="testsuite"

  global:
    # Cross-compile for amd64 only to speed up testing.
    - GOX_FLAGS="-arch amd64"
    - MACOSX_DEPLOYMENT_TARGET=10.15

addons:
  apt:
    update: true
    packages:
      - python-virtualenv

before_install:
  - python --version
  # Redo the travis setup but with the elastic/libbeat path. This is needed so the package path is correct
  - mkdir -p $HOME/gopath/src/github.com/radoondas/netatmobeat/
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/radoondas/netatmobeat/
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/radoondas/netatmobeat/
  - cd $HOME/gopath/src/github.com/radoondas/netatmobeat/
  - if [ $TRAVIS_OS_NAME = osx ]; then pip install virtualenv; fi

install:
  - true

script:
  - make $TARGETS

after_success:
  # Copy full.cov to coverage.txt because codecov.io requires this file
