netatmobeat:
  client_id: "abcdefghijklmn"
  client_secret: "mysecretfromapp"

  username: "user@email"
  password: "password"

  public_weather:
    enabled: true
    period: 10m
    regions:
      - region:
        enabled: true
        name: "EMEA"
        description: "Slovakia"
        lat_ne: 49.650266
        lon_ne: 22.780239
        lat_sw: 47.780377
        lon_sw: 16.759731
      - region:
        enabled: true
        name: "Spain"
        description: "Somewhere in EU"
        lat_ne: 43.417618
        lon_ne: 3.569562
        lat_sw: 36.867098
        lon_sw: -9.438251
      - region:
        enabled: true
        name: "Canada"
        description: "Somewhere in Canada"
        lat_ne: 59.999575
        lon_ne: -109.983298
        lat_sw: 49.085200
        lon_sw: -119.817889
      - region:
        enabled: true
        name: "Canada"
        description: "Somewhere in Canada"
        lat_ne: 59.991157
        lon_ne: -94.813006
        lat_sw: 49.056411
        lon_sw: -110.062029
      - region:
        enabled: true
        name: "Hawai"
        description: "Hawai"
        lat_ne: 22.289007
        lon_ne: -154.135656
        lat_sw: 18.789029
        lon_sw: -160.756554

  weather_stations:
    enabled: false
    period: 5m
    ids: [ "st:at:io:ni:dd" ]
processors:
- add_cloud_metadata: ~
- add_docker_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
